### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by johntdavis84** [MatthewVance/unbound-docker-rpi#18]
Hello!

My apologies in advance for what is most likely a profoundly stupid question. ;)

I just installed an updated image this morning. Is there a changeling somewhere?

**Comment by MatthewVance** [comment]
No, there's not. Only Git history. Periodically, I'll push a new build as
latest without code changes. It is to pull in an updated base image and
refresh apt get packages.

**Comment by MatthewVance** [comment]
Duplicate of https://github.com/MatthewVance/unbound-docker-rpi/issues/11
