### ISSUE TITLE
Use a customized Unbound configuration  command

### ISSUE THREAD

**Issue by gkalemis** [MatthewVance/unbound-docker-rpi#2]
command has very small error in repo name (a dash is missing)

Should be changed to

docker run --name=unbound-rpi \
--volume=/my-directory/unbound:/opt/unbound/etc/unbound/ \
--publish=53:53/tcp \
--publish=53:53/udp \
--restart=unless-stopped \
--detach=true \
mvance/unbound-rpi:latest

**Comment by MatthewVance** [comment]
Thanks for catching and reporting this.
