### ISSUE TITLE
not copying *records.conf files on install

### ISSUE THREAD

**Issue by danchristal** [MatthewVance/unbound-docker-rpi#29]
Fresh container install is missing the 'a-records.conf', 'forward-records.conf', and 'srv-records.conf' files within the mounted volume for '/opt/unbound/etc/unbound' resulting in endless restart loops within docker. 

Work around is just create each of these files using touch

**Comment by MatthewVance** [comment]
What command are you using to run it?

**Comment by MatthewVance** [comment]
Closing due to no response. Feel free to re-open if this is still an issue.
