### ISSUE TITLE
Container binds to port 53 on TCP and UDP with no way to change

### ISSUE THREAD

**Issue by ZombieBear** [MatthewVance/unbound-docker-rpi#30]
Trying to set up the container to use as a recursive resolver for  pi-hole, the container always attempt to bind to port 53 even after changing the configuration, causing the container to continuously restart due to the port already being in use

**Comment by MatthewVance** [comment]
The way to solve this is Docker port mapping, not changing the Unbound config. 

https://github.com/MatthewVance/unbound-docker/issues/35

**Comment by MatthewVance** [comment]
Feel free to re-open if you have further questions.
