### ISSUE TITLE
Exec Format Error

### ISSUE THREAD

**Issue by Fiji05** [MatthewVance/unbound-docker-rpi#40]
Running in docker-compose using the examples provided and those I've seen online. Whenever I check the logs for why it is not properly starting, I see that there is an error

exec /unbound.sh: exec format error

I am on the latest version and just pulled it from docker.

**Comment by snaky69** [comment]
Can you share your compose file?

**Comment by Fiji05** [comment]
Embarrassing mistake lol, using the wrong repo. Nothing is wrong, sorry.

**Comment by MatthewVance** [comment]
I’m glad it is working for you now. On Dec 11, 2022, at 4:38 PM, Parker M. ***@***.***> wrote:﻿
Closed #40 as completed.
