### ISSUE TITLE
Updated version on par with non rpi version (1.18.0)

### ISSUE THREAD

**Issue by seanob86** [MatthewVance/unbound-docker-rpi#46]
There has been no update since 1.17.1, while the non-rpi version continues to be maintained (which is at v1.18.0 for latest) https://github.com/MatthewVance/unbound-docker

**Comment by BobbieERay** [comment]
I agree. I guess this image is no longer being maintained. If anyone knows of any alternatives, please let us know. Thank you.

**Comment by seanob86** [comment]
> I agree. I guess this image is no longer being maintained. If anyone knows of any alternatives, please let us know. Thank you.

I’m using this [image](https://github.com/klutchell/unbound-docker) now.
