### ISSUE TITLE
HEALTHCHECK for customised port

### ISSUE THREAD

**Issue by x-Felix** [MatthewVance/unbound-docker-rpi#6]
`HEALTHCHECK --interval=5s --timeout=3s --start-period=5s CMD drill @127.0.0.1 cloudflare.com || exit 1 `

If unbound.conf is set to use non 53 port, container healthcheck will always show unhealthy.
Is there better way to check the service status?

**Comment by MatthewVance** [comment]
Why not let the container run on 53 and just expose another port publicly?
-p 5353:53

Otherwise, update the Docker file and rebuild or rely on something like
Prometheus.

**Comment by x-Felix** [comment]
I use docker-compose.yml to disable healthcheck for this container. I don’t want it keeps query Cloudflare.
`healthcheck:
  disable: true `

**Comment by CamelT0E** [comment]
> I use docker-compose.yml to disable healthcheck for this container. I don’t want it keeps query Cloudflare. `healthcheck: disable: true `

I also have many request to Cloudflare in AdGuard home. These are provided by Unbound. Unfortunately, the different settings do not work.

I have tried:
```
healthcheck:
   disable: true
```
```
healthcheck:
  test: ["NONE"]
```
```
healthcheck:
   test: ["CMD", "true"]
```

Is there another tip on how to turn off this healthcheck?
@MatthewVance, It would be possible to disable the healthcheck in the unbound.conf or as an environment?
